class TransactionModel:
    id: int
    source_account_id: int
    destination_account_id: int
    amount: int
    message: str
    status: str
    fees: int
    kind: str
    tries: int
    timestamp: int
    updated_at: int
